// mongo ministerio query_mongo_csv.js > out.csv

print("_id;imei;imsi;msisdn;app_version;send_timestamp;receive_timestamp;timestamp;device_software_version;sim_serial_number;network_technology;network_type;cell_id;bsc;rnc;e_node_b;area_code;psc;pci;gsm_rx_level;gsm_rx_quality;umts_rscp;umts_rssi;umts_ecio;lte_rssi;lte_rsrp;lte_rsrq;lte_snr;lte_cqi;plmn;sim_plmn;sim_operator;roaming_type;battery_level;cpu_usage;cpu_temp;signal_level;signal_quality;incoming_call_start;outgoing_call_start;incoming_pickup_call;incoming_call_end;outgoing_call_end;missed_call;call_number;sms_in;sms_out;sms_number;data_in;data_out;app_data_usage;latitude;longitude");

db.getCollection('measurements').find({'imsi': '214040113765982' ,'timestamp': {$gt: '2015-06-11 00:00:00.000', $lt: '2015-06-12 23:59:59.000'}}).forEach(function(measurements){
	print(measurements._id.valueOf() + ";" + measurements.imei + ";" +measurements.imsi + ";" + measurements.msisdn + ";" + measurements.app_version + ";" + measurements.send_timestamp + ";" + measurements.receive_timestamp + ";" + measurements.timestamp + ";" + measurements.device_software_version + ";" + measurements.sim_serial_number + ";" + measurements.network_technology + ";" + measurements.network_type + ";" + measurements.cell_id + ";" + measurements.bsc + ";" + measurements.rnc + ";" + measurements.e_node_b + ";" + measurements.area_code + ";" + measurements.psc + ";" + measurements.pci + ";" + measurements.gsm_rx_level + ";" + measurements.gsm_rx_quality + ";" + measurements.umts_rscp + ";" + measurements.umts_rssi + ";" + measurements.umts_ecio + ";" + measurements.lte_rssi + ";" + measurements.lte_rsrp + ";" + measurements.lte_rsrq + ";" + measurements.lte_snr + ";" + measurements.lte_cqi + ";" + measurements.plmn + ";" + measurements.sim_plmn + ";" + measurements.sim_operator + ";" + measurements.roaming_type + ";" + measurements.battery_level + ";" + measurements.cpu_usage + ";" + measurements.cpu_temp + ";" + measurements.signal_level + ";" + measurements.signal_quality + ";" + measurements.incoming_call_start + ";" + measurements.outgoing_call_start + ";" + measurements.incoming_pickup_call + ";" + measurements.incoming_call_end + ";" + measurements.outgoing_call_end + ";" + measurements.missed_call + ";" + measurements.call_number + ";" + measurements.sms_in + ";" + measurements.sms_out + ";" + measurements.sms_number + ";" + measurements.data_in + ";" + measurements.data_out + ";" + measurements.app_data_usage + ";" + measurements.latitude + ";" + measurements.longitude);
});




